server_name: node03
server_id: 3
log_store: .raft/node03/log_store.bolt
stable_store: .raft/node03/stable_store.bolt
transport: 127.0.0.1:3003
servers:
  - id: 1
    address: 127.0.0.1:3001
  - id: 2
    address: 127.0.0.1:3002
  - id: 3
    address: 127.0.0.1:3003
