server_name: node01
server_id: 1
log_store: .raft/node01/log_store.bolt
stable_store: .raft/node01/stable_store.bolt
transport: 127.0.0.1:3001
servers:
  - id: 1
    address: 127.0.0.1:3001
  - id: 2
    address: 127.0.0.1:3002
  - id: 3
    address: 127.0.0.1:3003
